# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
# Mod Properties
mod_version=1.0.2
maven_group=me.noryea
archives_base_name=better-attack-reset
# Dependencies
# check this on https://fabricmc.net/develop/
fabric_version=0.155.2+26.2

#systemProp.http.proxyHost=127.0.0.1
#systemProp.https.proxyHost=127.0.0.1
#systemProp.http.proxyPort=7897
#systemProp.https.proxyPort=7897